server:
  port: 8080

spring:
  datasource:
#	url: jdbc:mysql://localhost:3306/flightdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    url: jdbc:mysql://rickyflightdb.cj6gcogsidzt.ap-southeast-2.rds.amazonaws.com:3306/flightdb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root1
    password: StrongPassword123456!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: a-very-long-secret-key-that-is-at-least-32-characters!
  expirationMs: 86400000

logging:
  level:
    org.hibernate.SQL: debug
